title: Yong Sook Prasit Attavit
logo: assets/img/Github_Pages_ProfilePhoto.png
description: Actively looking for opportunities to transition into the field of data analytics
show_downloads: false
theme: jekyll-theme-minimal
