title: Yong Sook Prasit Attavit
logo: assets/img/Github_Pages_ProfilePhoto.png
description: MS CS @ Georgia Tech; AI Engineer | Data Scientist | BI Developer
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jemoji
